// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/mergent-go/pkg/models/shared"
	"net/http"
)

type BatchCreateTasksRequest struct {
	Request []shared.TaskNewInput `request:"mediaType=application/json"`
}

type BatchCreateTasksResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Not Found
	Error *shared.Error
	// Created
	Tasks []shared.TaskOutput
}
