// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/mergent-go/pkg/models/shared"
	"net/http"
)

type DeleteTaskPathParams struct {
	// Task ID
	TaskID string `pathParam:"style=simple,explode=false,name=task_id"`
}

type DeleteTaskRequest struct {
	PathParams DeleteTaskPathParams
}

type DeleteTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Not Found
	Error *shared.Error
}
