// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/mergent-go/pkg/models/shared"
	"net/http"
)

type GetSchedulePathParams struct {
	// Schedule ID
	ScheduleID string `pathParam:"style=simple,explode=false,name=schedule_id"`
}

type GetScheduleRequest struct {
	PathParams GetSchedulePathParams
}

type GetScheduleResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Not Found
	Error *shared.Error
	// OK
	Schedule *shared.Schedule
}
