// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"github.com/speakeasy-sdks/mergent-go/pkg/models/shared"
	"net/http"
)

type UpdateTaskPathParams struct {
	// Task ID
	TaskID string `pathParam:"style=simple,explode=false,name=task_id"`
}

type UpdateTaskRequest struct {
	PathParams UpdateTaskPathParams
	Request    shared.TaskInput `request:"mediaType=application/json"`
}

type UpdateTaskResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Not Found
	Error *shared.Error
	// OK
	Task *shared.TaskOutput
}
