// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

// Error - Unprocessable Entity
type Error struct {
	// If multiple errors occured (e.g., with param validation), the list of errors that occured.
	Errors []Error `json:"errors,omitempty"`
	// A human-readable message providing more details about the error(s).
	Message *string `json:"message,omitempty"`
	// If the error is parameter-specific, the parameter related to the error.
	Param *string `json:"param,omitempty"`
}
