// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type SchemeBasic struct {
	Password string `security:"name=password"`
	Username string `security:"name=username"`
}

type SchemeBearer struct {
	Authorization string `security:"name=Authorization"`
}

type Security struct {
	Basic  *SchemeBasic  `security:"scheme,type=http,subtype=basic"`
	Bearer *SchemeBearer `security:"scheme,type=http,subtype=bearer"`
}
